# -*- coding: utf-8 -*-
"""Practical3_MultipleLinearRegression_StudentPerformance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DHbmdGH9lX7JATazJZYIzCElG41Dg9gF
"""

import pandas as pd
data = pd.read_csv('/content/Student_Performance.csv')
#data['Performance Index'] = data.target
numeric_data = data.select_dtypes(include=['number'])
corr=numeric_data.corr()

print(corr['Performance Index'])
data.head()

import seaborn as sns
import matplotlib.pyplot as plt

# Assuming 'housing_df' is the DataFrame cont
plt.figure(figsize=(10, 8))
sns.heatmap(numeric_data.corr(), annot=True, cmap='coolwarm')
plt.title('Correlation Matrix')
plt.show()

X = data[['Hours Studied', 'Previous Scores', 'Sleep Hours', 'Sample Question Papers Practiced']]
y = data['Performance Index']

from sklearn.model_selection import train_test_split
X_train,X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, y_pred)
print(f'Mean Squared Error: {mse}')

print("Coefficients:", model.coef_)
print("Intercept:", model.intercept_)

import matplotlib.pyplot as plt
plt.scatter(y_test, y_pred, color='blue', label='Actual Data')  # Scatter plot for original data
plt.plot(y_test, y_test, color='red', label='Regression Line')  # Regression line
plt.title('Linear Regression Fit')
plt.xlabel('X (Independent Variable)')
plt.ylabel('y (Dependent Variable)')
plt.legend()
plt.show()